[tool.poetry]
name = "idc-path-annotations"
version = "0.1.0"
description = "Python code for converting TCGA annotations into DICOM format."
authors = ["Chris Bridge <cbridge@mgh.harvard.edu>"]
readme = "README.md"
packages = [{include = "idc_path_annotations"}]

[tool.poetry.dependencies]
python = "^3.11"
pydicom = "^2.3.1"
highdicom = "^0.20.0"
pycrumbs = "^0.1.3"
google = "^3.0.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
mypy = "^1.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
